# Generated by Django 3.1 on 2022-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20220508_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(height_field='img_height', upload_to='', verbose_name='Фотография', width_field='img_width'),
        ),
    ]
