# Generated by Django 3.1 on 2022-05-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20220509_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='img_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(height_field='img_height', upload_to='', verbose_name='Фотография', width_field='img_width'),
        ),
    ]
